name: CI # Continuous Integration

on:
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check format
        run: cargo fmt --check --all
